#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import slot_provisioning


json.dump(slot_provisioning.slot_port_ranges(), fp=sys.stdout)

