#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

data = json.load(sys.stdin)

# Check if fqdn field is present
fqdn = data["fqdn"] if "fqdn" in data else os.environ["KML_DEFAULT_FQDN"]

# Chceck if the letsencrypt field is present
if "lets_encrypt" in data:
    agent.set_certificate(
            {'fqdn': fqdn,
            'lets_encrypt': data['lets_encrypt'],
            }
        )

# if all previous steps are successful, set the FQDN
agent.set_env("KML_DEFAULT_FQDN", fqdn)
