#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

if str(event['node']) != os.environ['NODE_ID']:
    print(agent.SD_DEBUG + "Event ignored: source is another node")
    sys.exit(2)

if event['domain']['main'] != os.environ["KML_DEFAULT_FQDN"]:
    print(agent.SD_DEBUG + "Event ignored: domain not used")
    sys.exit(3)
