#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

kamailio_certs_path = "kamailio-certificates"

domains_list = [f.name for f in os.scandir(kamailio_certs_path) if f.is_dir()]

if event['domain']['main'] not in domains_list:
    print(agent.SD_DEBUG + "Event ignored: domain not used")
    sys.exit(3)
