#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# JSON input from standard input
json_input=$(cat)

# Use jq to extract ['domain']['main']
DOMAIN=$(echo "$json_input" | jq -r '.domain.main')

# Create certificate tls configuration
generate_tls_config ${DOMAIN}
