#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import subprocess

event = json.load(sys.stdin)
myname = os.environ["KML_DEFAULT_FQDN"]

if not agent.certificate_event_matches(event, myname):
    sys.exit(0) # ignore event if not relevant

# Obtain the changed certificate and its private key
get_proc = agent.run_helper(
    'get-certificate',
    f'--cert-file=kamailio-certificate/cert_files/{myname}.crt',
    f'--key-file=kamailio-certificate/cert_files/{myname}.key',
    myname,
)

# Reload the running service if the certificate differs
if get_proc.returncode == 0:
    subprocess.run(['podman', 'exec', '-i', 'kamailio', 'kamcmd'], input='tls.reload\n', text=True, stdout=subprocess.DEVNULL)
