#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

from domain_routes import run_route_query

data = json.load(sys.stdin)

route = run_route_query(data['domain'], """
SELECT CASE WHEN EXISTS (SELECT FROM selected_route) THEN
    json_build_object('address', (
        SELECT coalesce(json_agg(json_build_object('uri', destination, 'description', description)), '[]'::json)
        FROM dispatcher WHERE setid = (SELECT setid FROM selected_route)
    ))
ELSE '{}'::json END;
""", read_only=True)

json.dump(json.loads(route), fp=sys.stdout)
