#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# sourcing the file directly is broken with quotes
POSTGRES_PASSWORD=$(grep '^POSTGRES_PASSWORD=' ./passwords.env) && export $POSTGRES_PASSWORD

# Loop for 30 seconds until the database is ready
for i in {1..30}; do
    if podman exec -e PGCONNECT_TIMEOUT=2 postgres psql -U $POSTGRES_USER $POSTGRES_DB -c "SELECT 1;" &> /dev/null; then
	break
    fi
    sleep 1
done

# Set the password for the postgres user
podman exec postgres psql -U $POSTGRES_USER $POSTGRES_DB -c "ALTER USER \"$POSTGRES_USER\" WITH PASSWORD '$POSTGRES_PASSWORD';" &> /dev/null

if [ $? -ne 0 ]; then
    echo "Failed to set the password for the postgres user"
    exit 1
fi
