#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Generate a self-signed certificate that includes the current machine FQDN
# and all machine IPs
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

mkdir -p kamailio-certificate/cert_files

addresses=''
for ip in $(ip -json addr show | jq -r '.[].addr_info | .[].local')
do
    addresses="$addresses,IP:$ip"
done

openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
	-subj "/CN=$KML_DEFAULT_FQDN"  -addext "subjectAltName=DNS:localhost,DNS:$KML_DEFAULT_FQDN$addresses" \
	-keyout kamailio-certificate/cert_files/$KML_DEFAULT_FQDN.key -out kamailio-certificate/cert_files/$KML_DEFAULT_FQDN.crt

generate_tls_config $KML_DEFAULT_FQDN
