#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
import slot_provisioning

agent.assert_exp(
    agent.add_public_service(
        os.environ['MODULE_ID'],
        slot_provisioning.public_service_ports(),
    )
)
