#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
import firewall

# Open legacy SIP/RTP ports plus any slot range defined through TRUNK_* envs.
# NAT-only ports 6060/6061 are still managed during configure-module.
agent.assert_exp(agent.add_public_service(
    os.environ['MODULE_ID'],
    firewall.get_public_service_ports(behind_nat=False),
))
