#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules to call our *-route actions by requiring the "routeadm" role
#
routeadm_actions=(
    add-route
    get-route
    remove-route
    list-routes
)
redis-exec SADD "${AGENT_ID}/roles/routeadm" "${routeadm_actions[@]}"

#
# Allow other modules to call our slot-domain actions by requiring the "trunkadm" role
#
trunkadm_actions=(
    add-slot-domain
    list-slot-domains
    remove-slot-domain
    list-slot-port-ranges
)
redis-exec SADD "${AGENT_ID}/roles/trunkadm" "${trunkadm_actions[@]}"

# Allow the module to call its own actions
redis-exec SADD "${AGENT_ID}/roles/selfadm" "*"
