#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules to call our *-route actions by requiring the "routeadm" role
#
routeadm_actions=(
    add-route
    get-route
    remove-route
    list-routes
)
redis-exec SADD "${AGENT_ID}/roles/routeadm" "${routeadm_actions[@]}"
