#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

systemctl --user daemon-reload

echo "Enabling systemd exporter"
systemctl --user enable --now systemd-exporter.service
