#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# HACK: This is a workaround for the fact environment variables are not relolad
# beetwen the steps of the update-module.d. This is a temporary solution until
# the issue is fixed.

runagent ${AGENT_INSTALL_DIR}/actions/configure-module/90srv
