#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

from domain_routes import run_route_query

data = json.load(sys.stdin)

run_route_query(data['domain'], """
WITH inserted AS (
    INSERT INTO nethvoice_proxy_routes (target, route_type)
    SELECT :'domain', 'domain' WHERE NOT EXISTS (SELECT FROM selected_route)
    RETURNING *
)
INSERT INTO selected_route SELECT * FROM inserted;

INSERT INTO domain (domain, did)
SELECT :'domain', :'domain' WHERE NOT EXISTS (SELECT FROM domain WHERE domain = :'domain');
INSERT INTO dialplan (dpid, pr, match_op, match_exp, match_len, subst_exp, repl_exp, attrs)
SELECT 1, 1, 0, :'domain', 0, '(.*)', setid::text, setid::text FROM selected_route
WHERE NOT EXISTS (SELECT FROM dialplan WHERE dpid = 1 AND match_exp = :'domain');

DELETE FROM dispatcher WHERE setid = (SELECT setid FROM selected_route);
INSERT INTO dispatcher (setid, destination, description)
SELECT setid, address->>'uri', address->>'description'
FROM selected_route, json_array_elements(:'addresses'::json) AS address;
""", data['address'])
