#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

config = {}
addresses = {}

service = {
        'adress': os.environ["SERVICE_IP"],
        'nethmask': os.environ["SERVICE_NET"],
        }

if os.environ["BEHIND_NAT"] ==  "true":
    addresses = {
            'address':os.environ['PRIVATE_IP'],
            'public_address': os.environ['PUBLIC_IP'],
            "service": service
            }
else:
    addresses =  {
            'address': os.environ["PUBLIC_IP"],
            'service': service
            }

config["addresses"] = addresses

config["fqdn"] = os.environ["KML_DEFAULT_FQDN"]

json.dump(config, fp=sys.stdout)
