#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

rdb = agent.redis_connect()
config = {}
result = []

config['sip_providers'] = agent.list_service_providers(rdb, 'sip', 'udp')
# Output the configuration as JSON to stdout
json.dump(config, fp=sys.stdout)
