#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent_id = os.getenv("AGENT_ID", "")
if not agent_id:
    raise Exception("AGENT_ID not found inside the environemnt")

# Connect to redis
rdb = agent.redis_connect(privileged=True)

#FIXME this is only a mockup
if "address"  in data:
    for addres in data["address"]:
        rdb.srem(f'{agent_id}/routers/{data["domain"]}', addres)

if rdb.scard(f'{agent_id}/routers/{data["domain"]}') == 0 or "address" not in data:
    rdb.delete(f'{agent_id}/routers/{data["domain"]}')
