#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='delete-certificate',
    data={'fqdn': data["domain"]},
)
# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
