#!/usr/bin/env python

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os

import agent


with open('routes_dump.json', 'r') as f:
    routes = json.load(f)
    for route in routes:
        response = agent.tasks.run(
                agent_id=os.environ['AGENT_ID'],
                action='add-route',
                data=route
                )
        agent.assert_exp(response['exit_code'] == 0)
