#!/usr/bin/env python

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import time

import agent


with open('slot_domains_dump.json', 'r') as f:
    slot_domains = json.load(f)
    for slot_domain in slot_domains:
        response = agent.tasks.run(
            agent_id=os.environ['AGENT_ID'],
            action='add-slot-domain',
            data={"domain": slot_domain["domain"]},
        )
        agent.assert_exp(response['exit_code'] == 0)
        # By default there is a rate limiting of maximum one reload in five
        # seconds to be waited before executing a new RPC reload. Executing two
        # RPC reloads of the same table at the same time can cause Kamailio to
        # crash.
        time.sleep(5)
