#!/usr/bin/env python

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import time

import agent


with open('routes_dump.json', 'r') as f:
    routes = json.load(f)
    for route in routes:
        response = agent.tasks.run(
                agent_id=os.environ['AGENT_ID'],
                action='add-route',
                data=route
                )
        agent.assert_exp(response['exit_code'] == 0)
        # By default there is a rate limiting of maximum one reload in five
        # seconds to be waited before executing a new RPC reload. Executing two
        # RPC reloads of the same table at the same time can cause Kamailio to
        # crash.
        # See: https://www.kamailio.org/docs/modules/stable/modules/permissions.html#permissions.p.reload_delta
        time.sleep(5)
