name: Test module

on:
  workflow_dispatch:
    inputs:
      debug_shell:
        description: "Debug shell"
        required: true
        type: boolean
  workflow_run:
    workflows: ["Publish images"]
    types: [completed]

jobs:
  run:
    name: "Run tests"
    uses: NethServer/ns8-github-actions/.github/workflows/test-module.yml@v1
    with:
      ui_tests_strategy: on_renovate_ui_change
      debug_shell: ${{ github.event.inputs.debug_shell == 'true' }}
    secrets:
      do_token: ${{ secrets.do_token }}
